### ISSUE TITLE
Reaper export: Text mit , erzeugt inkompatbiles CSV

### ISSUE THREAD

**Issue by saerdnaer** [shownotes/tinyOSF.js#13]
Wenn die Shownoter in ihrem Text nen Komma verwenden bringt das Reaper durcheinander und es weigert sich das CSV zu importieren. Reaper selbst packt in solchen Fällen den Text in Anführungszeichen ("). Kommt ein Anführungszeichen im Text vor wird es mit " escapt. 

Beispiel export aus Reaper:
```
#,Name,Start,End,Length
R1,"test, b """,0:01:19:22,0:05:35:15,0:04:15:17
```

Den ersten Teil hab ich hier mal "gelöst" https://github.com/saerdnaer/tinyOSF.js/commit/994fe697111bfd7366214115d7e252b0654d798c allerdings fehlt halt der zweite Teil. (Ich bin nicht mehr ganz so fit in JavaScript)

**Comment by saerdnaer** [comment]
Was ist den der aktuelle Stand? Woran hängt es den noch? Komma, im Text einer Kapitelmarken manchen den Reaper Export immer noch kaputt.

**Comment by SimonWaldherr** [comment]
Hi, sorry, ich war/bin beruflich sehr stark ausgelastet.
Das Export Modul sollte jetzt funktionieren.
Für shownot.es ist allerdings mittlerweile https://github.com/shownotes/osf-export-templates/blob/master/tpls/reaper.tpl zuständig.

![reaper](https://cloud.githubusercontent.com/assets/198920/7339817/b31374e4-ec7b-11e4-8f4b-502c6f65ec28.jpg)
